media_extensions:
    video: [mp4, mov]
    audio: [mp3]
    image: [png, jpg, jpeg]

media_search_directories: [
      /media,
      /home/pi,
    ]

playback_commands:
    video: omxplayer $1
    audio: omxplayer $1
    image: omxplayer $1

playerd:
    port: 5556
