media_extensions:
    video: [mp4, mov, avi]
    audio: [mp3]
    image: [png, jpg, jpeg]

media_search_directories: [
      /media,
      /home/pi,
      /Users/chris/Movies,
      /Users/chris/Projects/Uli/Testvideos_2/videos,
      /tmp,
    ]

playback_commands:
    video: /Users/chris/Tools/mplayer2.app/Contents/MacOS/mplayer2 $1
    audio: omxplayer $1
    image: omxplayer $1

playerd:
    port: 5556